# -*- coding: utf-8 -*-
"""Integers Come In All Sizes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DbB54zAq7SeUyv7POrtw_epoH1FWB1Ml
"""

'''Task-  
Read four numbers, a, b, c, and d, and print the result of a^b + c^d.
Input Format :
Integers a, b, c, and d are given on four separate lines, respectively.
'''
a = int(input())
b = int(input())
c = int(input())
d = int(input())

print(pow(a,b)+pow(c,d))

2