# -*- coding: utf-8 -*-
"""Power - Mod Power.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DbB54zAq7SeUyv7POrtw_epoH1FWB1Ml
"""

'''Task-  
You are given three integers: a, b, and m, respectively. Print two lines.
The first line should print the result of pow(a,b). The second line should print the result of pow(a,b,m).

Input Format :
The first line contains a, the second line contains b, and the third line contains m.

'''
a = int(input())
b = int(input())
m = int(input())

print(pow(a,b))
print(pow(a,b,m))

