# -*- coding: utf-8 -*-
"""Group(), Groups() & Groupdict().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DbB54zAq7SeUyv7POrtw_epoH1FWB1Ml
"""

import re
expss = r"([a-zA-Z0-9])\1+"
m = re.search(expss,input())
if m:
    print(m.group(1))
else:
    print(-1)

|