# -*- coding: utf-8 -*-
"""Arithmetic Operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DbB54zAq7SeUyv7POrtw_epoH1FWB1Ml
"""

'''Task-3
The provided code stub reads two integers from STDIN, a and b. 
Add code to print three lines where:

1.The first line contains the sum of the two numbers.
2.The second line contains the difference of the two numbers (first - second).
3.The third line contains the product of the two numbers.'''

a = int(input())
b = int(input())
      
c = a+b
print('c=', c)
    
d = a-b
print('d=',d)
    
e=a*b
print('e=', e)