# -*- coding: utf-8 -*-
""""Hello, World!".ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ezMU5VbNsGt7LQXk3-7H7naWcXsbIc5L
"""

#Task-1
#Here is a sample line of code that can be executed in Python:

print("Hello, World!")

