# -*- coding: utf-8 -*-
"""Python If-Else.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DbB54zAq7SeUyv7POrtw_epoH1FWB1Ml
"""

'''Task-2
Given an integer, n, perform the following conditional actions:

If  is odd, print Weird
If  is even and in the inclusive range of 2 to 5, print Not Weird
If  is even and in the inclusive range of 6 to 20, print Weird
If  is even and greater than 20, print Not Weird'''


import math
import os
import random
import re
import sys



n = int(input())
if n%2 != 0:
    print('Weird')
elif 2<=n<=5:
    print('Not Weird')
elif 6<=n<=20:
    print('Weird')
elif n>20:
    print('Not Weird')

