# -*- coding: utf-8 -*-
"""Python: Division.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DbB54zAq7SeUyv7POrtw_epoH1FWB1Ml
"""

'''Task-3
The provided code stub reads two integers, a and b, from STDIN.
Add logic to print two lines. 
The first line should contain the result of integer division, a//b . T
he second line should contain the result of float division,  a/b .
No rounding or formatting is necessary.'''

a = int(input())
b = int(input())
      
    
x = a//b
print('x=', x)

y = a/b
print('y=', y)

