# -*- coding: utf-8 -*-
"""Python: Loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DbB54zAq7SeUyv7POrtw_epoH1FWB1Ml
"""

'''Task-5
Task
The provided code stub reads and integer, n, from STDIN. For all non-negative integers i<n, print i^2.'''

n = int(input())
for i in range(0,n):
  print(i**2)