# -*- coding: utf-8 -*-
"""Python:Print Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DbB54zAq7SeUyv7POrtw_epoH1FWB1Ml
"""

'''Task-
The included code stub will read an integer, , from STDIN.
Without using any string methods, try to print the following:
Note that "..." represents the consecutive values in between.'''

n = int(input())
for i in range(n):
  print(i+1,end="")