# -*- coding: utf-8 -*-
"""Find a string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DbB54zAq7SeUyv7POrtw_epoH1FWB1Ml
"""

'''Task-  
Input Format:
The first line of input contains the original string. The next line contains the substring.

Output Format:
Output the integer number indicating the total number of occurrences of the substring in the original string.'''

def count_substring(string, sub_string):
    ml = len(string)
    sl = len(sub_string)
    count=0

    for i in range(ml-sl+1):
        if(string[i:(i+sl)]==sub_string):
            count+=1
            
    return count

if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

