# -*- coding: utf-8 -*-
"""Shape and Reshape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DbB54zAq7SeUyv7POrtw_epoH1FWB1Ml
"""

print(numpy.array(input().split(), int).reshape(3, 3))

|